### ISSUE TITLE
PANIC: runtime error: slice bounds out of range [42:7]

### ISSUE THREAD

**Issue by KyleSanderson** [moistari/rls#5]
panic: runtime error: slice bounds out of range [42:7]
goroutine 69 [running]:
golang.org/x/text/transform.String({0x82c548, 0xc000079470}, {0xc0015f2310, 0x7})
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:650 +0xbe5
github.com/moistari/rls.MustNormalize(...)
	/go/pkg/mod/github.com/moistari/rls@v0.2.6/rls.go:1013
main.getFormattedTitle({0x9, {0x0, 0x0}, {0xc0015f2290, 0xd}, {0xc0015f2310, 0x7}, {0x0, 0x0}, {0x0, ...}, ...})
	/app/main.go:256 +0xc6
main.processReleasesLoop(0xc000407080?, {{0x0, 0x0}, {0xc00062e498, 0x11}, 0x1f90, {0xc0002ff9fc, 0x4}, {0xc0002ffa00, 0x8}, ...})
	/app/main.go:146 +0x745
created by main.(*clientmap).getEntries
	/app/main.go:106 +0x345

**Comment by KyleSanderson** [comment]
panic: runtime error: slice bounds out of range [50:0]
goroutine 69 [running]:
golang.org/x/text/transform.(*link).src(...)
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:370
golang.org/x/text/transform.(*chain).Transform(0xc00010d470, {0xc000c04700?, 0x0?, 0x0?}, {0xc000c04780?, 0x0?, 0x0?}, 0x1)
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:422 +0x790
golang.org/x/text/transform.String({0x82c548, 0xc00010d470}, {0xc001f311c0, 0x32})
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:652 +0x842
github.com/moistari/rls.MustNormalize(...)
	/go/pkg/mod/github.com/moistari/rls@v0.2.6/rls.go:1013
main.getFormattedTitle({0x9, {0x0, 0x0}, {0xc001f311c0, 0x32}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/app/main.go:256 +0x89
main.processReleasesLoop(0xc000fbc0c0?, {{0x0, 0x0}, {0xc00001c078, 0x11}, 0x1f90, {0xc0004e204c, 0x4}, {0xc0004e2050, 0x8}, ...})
	/app/main.go:146 +0x745
created by main.(*clientmap).getEntries
	/app/main.go:106 +0x345
panic: runtime error: slice bounds out of range [50:0]
goroutine 24 [running]:
golang.org/x/text/transform.(*link).src(...)
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:370
golang.org/x/text/transform.(*chain).Transform(0xc00010d470, {0xc0012f6b00?, 0x7ad?, 0x0?}, {0xc0012f6b80?, 0x0?, 0x0?}, 0x1)
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:422 +0x790
golang.org/x/text/transform.String({0x82c548, 0xc00010d470}, {0x0, 0x0})
	/go/pkg/mod/golang.org/x/text@v0.3.7/transform/transform.go:601 +0x1f3
github.com/moistari/rls.MustNormalize(...)
	/go/pkg/mod/github.com/moistari/rls@v0.2.6/rls.go:1013
main.getFormattedTitle({0x9, {0x0, 0x0}, {0xc000201b10, 0xd}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/app/main.go:256 +0x4c
main.processReleasesLoop(0xc00009a420?, {{0x0, 0x0}, {0xc000598030, 0x11}, 0x1f90, {0xc0000f831c, 0x4}, {0xc0000f8350, 0x8}, ...})
	/app/main.go:146 +0x745
created by main.(*clientmap).getEntries
	/app/main.go:106 +0x345

**Comment by KyleSanderson** [comment]
`s := fmt.Sprintf("%s%s%s%04d%02d%02d%02d%03d", rls.MustNormalize(r.Artist), rls.MustNormalize(r.Title), rls.MustNormalize(r.Subtitle), r.Year, r.Month, r.Day, r.Series, r.Episode)`

This is what my code looks like where this seems to fail...
